package proyectosaltoformularios;

public class Ventana_Secundaria_02 extends javax.swing.JFrame {

    public Ventana_Secundaria_02() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVSec2 = new javax.swing.JPanel();
        lblTituloVSec2 = new javax.swing.JLabel();
        btnVPpal = new javax.swing.JButton();
        lblDir = new javax.swing.JLabel();
        lblFono = new javax.swing.JLabel();
        lblDatoDireccion = new javax.swing.JLabel();
        lblDatoFono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ventana Secundaria 02");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVSec2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloVSec2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloVSec2.setText("Ventana Secundaria 02");
        panelVSec2.add(lblTituloVSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btnVPpal.setText("Ventana Principal");
        btnVPpal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVPpalActionPerformed(evt);
            }
        });
        panelVSec2.add(btnVPpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        lblDir.setText("Dirección:");
        panelVSec2.add(lblDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        lblFono.setText("Fono:");
        panelVSec2.add(lblFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        lblDatoDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDatoDireccion.setText("DATO_DIR");
        panelVSec2.add(lblDatoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 95, -1, -1));

        lblDatoFono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDatoFono.setText("DATO_FONO");
        panelVSec2.add(lblDatoFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 142, -1, -1));

        getContentPane().add(panelVSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVPpalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVPpalActionPerformed
        Principal.mostrarVentanaPrincipal();
    }//GEN-LAST:event_btnVPpalActionPerformed

    // Método para actualizar los datos mostrados en las etiquetas
    public void setDatos(String d1, String d2) {
        lblDatoDireccion.setText(d1);
        lblDatoFono.setText(d2);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVPpal;
    private javax.swing.JLabel lblDatoDireccion;
    private javax.swing.JLabel lblDatoFono;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblFono;
    private javax.swing.JLabel lblTituloVSec2;
    private javax.swing.JPanel panelVSec2;
    // End of variables declaration//GEN-END:variables
}
