package proyectosaltoformularios;

public class Ventana_Secundaria_01 extends javax.swing.JFrame {
      
    public Ventana_Secundaria_01() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVSec1 = new javax.swing.JPanel();
        lblTituloVSec1 = new javax.swing.JLabel();
        btnVPpal = new javax.swing.JButton();
        lblNom = new javax.swing.JLabel();
        lblApe = new javax.swing.JLabel();
        lblDatoNombre = new javax.swing.JLabel();
        lblDatoApellido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ventana Secundaria 01");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVSec1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloVSec1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloVSec1.setText("Ventana Secundaria 01");
        panelVSec1.add(lblTituloVSec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btnVPpal.setText("Ventana Principal");
        btnVPpal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVPpalActionPerformed(evt);
            }
        });
        panelVSec1.add(btnVPpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        lblNom.setText("Nombre:");
        panelVSec1.add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        lblApe.setText("Apellido:");
        panelVSec1.add(lblApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        lblDatoNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDatoNombre.setText("DATO_NOMBRE");
        panelVSec1.add(lblDatoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        lblDatoApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDatoApellido.setText("DATO_APELLIDO");
        panelVSec1.add(lblDatoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 145, -1, -1));

        getContentPane().add(panelVSec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVPpalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVPpalActionPerformed
        Principal.mostrarVentanaPrincipal();
    }//GEN-LAST:event_btnVPpalActionPerformed

    // Método para actualizar los datos mostrados en las etiquetas
    public void setDatos(String d1, String d2) {
        lblDatoNombre.setText(d1);
        lblDatoApellido.setText(d2);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVPpal;
    private javax.swing.JLabel lblApe;
    private javax.swing.JLabel lblDatoApellido;
    private javax.swing.JLabel lblDatoNombre;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblTituloVSec1;
    private javax.swing.JPanel panelVSec1;
    // End of variables declaration//GEN-END:variables
}
