package traductornumeros_igu;

public class IguTraductorNumeros extends javax.swing.JFrame {

    public IguTraductorNumeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        comboxnum = new javax.swing.JComboBox<>();
        lblTraduccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traductor de Números");

        comboxnum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        comboxnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxnumActionPerformed(evt);
            }
        });

        lblTraduccion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTraduccion.setText("Zero");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(comboxnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lblTraduccion)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTraduccion)
                    .addComponent(comboxnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboxnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxnumActionPerformed
        String opc = (String) comboxnum.getSelectedItem();
        switch (opc) {
            case "0":
                lblTraduccion.setText("Zero");
                break;
            case "1":
                lblTraduccion.setText("One");
                break;
            case "2":
                lblTraduccion.setText("Two");
                break;
            case "3":
                lblTraduccion.setText("Three");
                break;
            case "4":
                lblTraduccion.setText("Four");
                break;
            case "5":
                lblTraduccion.setText("Five");
                break;
            case "6":
                lblTraduccion.setText("Six");
                break;
            case "7":
                lblTraduccion.setText("Seven");
                break;
            case "8":
                lblTraduccion.setText("Eight");
                break;
            case "9":
                lblTraduccion.setText("Nine");
                break;
        }
    }//GEN-LAST:event_comboxnumActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JComboBox<String> comboxnum;
    private javax.swing.JLabel lblTraduccion;
    // End of variables declaration//GEN-END:variables
}
